# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import warnings
warnings.simplefilter('ignore')

import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

import pylab as plt
%matplotlib inline


# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
# Your code here:

from sklearn.datasets import load_diabetes

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [3]:
# Your code here:
data=pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)



In [4]:
data['target']=load_diabetes().target

In [5]:
data.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0

In [6]:
diabetes = load_diabetes()

In [7]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [8]:
# Your code here:
diabetes["DESCR"].split("\n")

['.. _diabetes_dataset:',
 '',
 'Diabetes dataset',
 '----------------',
 '',
 'Ten baseline variables, age, sex, body mass index, average blood',
 'pressure, and six blood serum measurements were obtained for each of n =',
 '442 diabetes patients, as well as the response of interest, a',
 'quantitative measure of disease progression one year after baseline.',
 '',
 '**Data Set Characteristics:**',
 '',
 '  :Number of Instances: 442',
 '',
 '  :Number of Attributes: First 10 columns are numeric predictive values',
 '',
 '  :Target: Column 11 is a quantitative measure of disease progression one year after baseline',
 '',
 '  :Attribute Information:',
 '      - age     age in years',
 '      - sex',
 '      - bmi     body mass index',
 '      - bp      average blood pressure',
 '      - s1      tc, total serum cholesterol',
 '      - s2      ldl, low-density lipoproteins',
 '      - s3      hdl, high-density lipoproteins',
 '      - s4      tch, total cholesterol / HDL',
 '      - s5    

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [9]:
# Your code here:

data.shape

(442, 11)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [10]:
# Your code here:
from sklearn.linear_model import LinearRegression as LinReg
from sklearn.metrics import r2_score as r2

Initialize the model in the variable `diabetes_model`

In [11]:
# Your code here:
diabetes_model=LinReg()

diabetes_model

LinearRegression()

In [12]:
x=data.drop('target', axis=1)

y=data.target

In [13]:
diabetes_model.fit(x, y)

LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [14]:
# Your code here:

diabetes_model.coef_

array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

In [15]:
diabetes_model.intercept_

152.1334841628965

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [16]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [17]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [18]:
# Your code here:

auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

In [19]:
auto.shape

(398, 8)

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [20]:
# Your code here:

auto.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 51.5 KB


What is the newest model year and the oldest model year?

In [21]:
# Your code here:

max(auto.model_year)

82

In [22]:
min(auto.model_year)

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [23]:
# Your code here:

auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [24]:
auto= auto.dropna()
auto.shape

(392, 8)

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [25]:
# Your code here:

auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [26]:
auto = auto.drop(['car_name'], axis=1)

In [27]:
auto.head(3)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   

   model_year  
0          70  
1          70  
2          70

In [28]:
# Import the necessary function
from sklearn.model_selection import train_test_split as tts


In [29]:
X=auto.drop('mpg', axis=1)

y=auto.mpg

In [30]:
# Your code here:
train, test = tts(auto)

train.shape, test.shape


((294, 7), (98, 7))

In [31]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, train_size=0.8, random_state=42)

In [32]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((313, 6), (79, 6), (313,), (79,))

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [33]:
# Your code here:
from sklearn.linear_model import LinearRegression as LinReg
from sklearn.metrics import r2_score, mean_squared_error 


In [34]:
linreg=LinReg()

linreg.fit(X_train, y_train)

LinearRegression()

In [35]:
linreg.coef_[:10]

array([-0.116173  ,  0.00101347, -0.00227634, -0.00656101,  0.06173551,
        0.76063644])

In [36]:
linreg.intercept_

-15.057758585282404

Next, fit the model in the cell below.

In [37]:
# Your code here:



# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [38]:
# Your code here:
y_pred=linreg.predict(X_test)

y_pred[:10]


array([25.93279618, 26.29927859, 32.96548909, 26.8544302 , 29.45372581,
       29.08699476,  7.63874768, 29.23704446, 20.87736024, 28.91582943])

In [39]:
y_pred.shape==y_test.shape



True

In [40]:
r2_score(y_test, y_pred)

0.794234907542859

In [41]:
mean_squared_error(y_test, y_pred, squared=False)

3.2407360783342583

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [42]:
# Your code here:
y_test_pred = linreg.score(X_test, y_test)
y_test_pred

0.794234907542859

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [43]:
# Your code here:
X_train09, X_test09, y_train09, y_test09 = tts(X, y, test_size=0.1, train_size=0.9, random_state=42)
X_train09.shape, X_test09.shape, y_train09.shape, y_test09.shape

((352, 6), (40, 6), (352,), (40,))

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [44]:
# Your code here:
auto_model09=LinReg()

auto_model09.fit(X_train09, y_train09)


LinearRegression()

In [45]:
auto_model09.coef_[:10]

array([-0.23653029,  0.00316396,  0.00250662, -0.00663075,  0.07263564,
        0.75032631])

In [47]:
auto_model09.intercept_

-14.551793731860915

Compute the predicted values and r squared score for our new model and new sample data.

In [48]:
# Your code here:
y_pred09=auto_model09.predict(X_test09)

y_pred09[:10]


array([25.79500879, 26.30607444, 32.72173147, 26.76455357, 29.32069319,
       28.92374612,  7.92293591, 29.07543422, 20.77292415, 28.65066633])

In [49]:
y_pred09.shape==y_test09.shape

True

In [50]:
r2_score(y_test09, y_pred09)

0.8468911998183242

In [51]:
mean_squared_error(y_test09, y_pred09, squared=False)

3.018292147138817

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [54]:
# Your code here:

improve = (r2_score(y_test09, y_pred09))-(r2_score(y_test, y_pred))
improve

0.0526562922754652

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [ ]:
# Your code here:



Fit the model and print the ranking

In [ ]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [ ]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [ ]:
# Your code here: 

